Parameters:
  ResourcePrefix:
    Description: Name used to prefix most resources
    Type: String
    Default: psyoptions-tracker
    AllowedPattern : "[a-z\\-]*"
  HasuraContainerPort:
    Type: Number
    Default: 8080
  TimescaleContainerPort:
    Type: Number
    Default: 5432
  HasuraImageURI:
    Type: String
  SerumVialImageURI:
    Type: String
  ListenerImageURI:
    Type: String
  DashboardImageURI:
    Type: String
  RpcUrl:
    Type: String
    Default: https://api.devnet.solana.com
  HostedZoneId:
    Type: String
  HasuraDomainName:
    Description: The fully qualified domain name the Hasura DNS record sets belong to
    Type: String
    Default: www.example.com
  HasuraDomainCertificateArn:
    Description: The ARN of the SSL/TLS certificate to use for the secure the Hasura load balancer listener
    Type: String
  Ec2KeyNameParam:
    Description: The name of the EC2 keypair that is default added to instances
    Type: String

Mappings: 
  RegionMap:
    us-east-1: 
      "TimescaleAmi": "ami-0313b4bfed0594a99"
    us-east-2: 
      "TimescaleAmi": "ami-0c5ddf9bfd0e62c37"
    us-west-1: 
      "TimescaleAmi": "ami-0e989ea8765644217"
    us-west-2: 
      "TimescaleAmi": "ami-0623161c84070eab1"
    eu-central-1:
      "TimescaleAmi": "ami-01a81696798f7f978"
    eu-north-1:
      "TimescaleAmi": "ami-0311515c2f7729997"
    eu-west-1: 
      "TimescaleAmi": "ami-0e0485cba3f4886ba"
    eu-west-2: 
      "TimescaleAmi": "ami-04cb5c2cf3fadd9dd"
    eu-west-3: 
      "TimescaleAmi": "ami-04cb5c2cf3fadd9dd"

Resources:
  # Create CloudWatch LogGroup for the task logs
  ContainerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        !Join ['-', [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'Container']]
      RetentionInDays: 7

  # Create an ECS Cluster
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['-', [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'Cluster']]
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  # Create a VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.10.0.0/16
      EnableDnsHostnames: True
      EnableDnsSupport: True

  # Create a Subnet
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.10.1.0/24
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', 'a']]
  # Create a Subnet
  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.10.2.0/24
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', 'b']]

  # Create a Private Subnet
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.10.3.0/24
      VpcId: !Ref VPC
      AvailabilityZone: !Join ['', [!Ref 'AWS::Region', 'a']]

  # Create a route table to allow access to internet
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  # Create a Route to allow access to internet using an internet gateway
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCInternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Attach Public Route to SubnetA
  SubnetAPublicRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SubnetA

  # Attach Public Route to SubnetB
  SubnetBPublicRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SubnetB

  # Create an Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  # Attach the internet gateway to the VPC
  VPCInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  # Create Access Role for ECS-Tasks
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        !Join ['-', [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'ExecutionRole']]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  # Create namespace for AWS Service Discovery
  PrivateNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
        Name: private-psyoptions.io
        Vpc: !Ref VPC
  
  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the PsyOptions Market Tracker
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
          - TTL: 60
            Type: SRV
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: !Join ['-', [!Ref ResourcePrefix, 'discovery-service']]
      NamespaceId: !Ref PrivateNamespace

  TimescaleSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Security group for ingress SSH and Timescale traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
        - IpProtocol: "-1"
          FromPort: 0
          ToPort: 65535
          CidrIp: 172.10.0.0/16
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: 0
          ToPort: 65535
          CidrIp: 172.10.0.0/16

  # Create the Hasura TaskDefinition with container details
  TimescaleTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - 'EC2'
      TaskRoleArn: !Ref ExecutionRole
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: !Join ['-', [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'Timescale']]
          Image: public.ecr.aws/s6m7j8l9/timescale/timescaledb:2.2.0-pg13
          ReadonlyRootFilesystem: false
          Environment:
            - Name: PORT
              Value: !Ref TimescaleContainerPort
            # TODO replace with secrests / parameters
            - Name: POSTGRES_DB
              Value: serum_markets
            - Name: POSTGRES_PASSWORD
              Value: password
            - Name: POSTGRES_USER
              Value: tracker
          PortMappings:
            - ContainerPort: !Ref TimescaleContainerPort
              HostPort: !Ref TimescaleContainerPort
          MemoryReservation: 1024
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref 'AWS::Region'
              awslogs-group:
                !Join ['-', [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'Container']]
              awslogs-stream-prefix: 'Timescale'

  # Create the Hasura TaskDefinition with container details
  HasuraTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Memory: 1024
      Cpu: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - 'FARGATE'
      TaskRoleArn: !Ref ExecutionRole
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: !Join ['-', [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'Hasura']]
          Image: !Ref HasuraImageURI
          Cpu: 512
          Memory: 1024
          ReadonlyRootFilesystem: false
          Environment:
            - Name: PORT
              Value: !Ref HasuraContainerPort
            - Name: HASURA_GRAPHQL_CORS_DOMAIN
              Value: "*"
              # TODO replace with secrests / parameters
            - Name: HASURA_GRAPHQL_DATABASE_URL
              Value: postgres://tracker:password@timescale.private-psyoptions.io/serum_markets
            - Name: HASURA_GRAPHQL_DEV_MODE
              Value: false
            - Name: HASURA_GRAPHQL_ENABLE_CONSOLE
              Value: true
            - Name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
              Value: startup, http-log, webhook-log, websocket-log, query-log
          PortMappings:
            - ContainerPort: !Ref HasuraContainerPort
              HostPort: !Ref HasuraContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref 'AWS::Region'
              awslogs-group:
                !Join ['-', [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'Container']]
              awslogs-stream-prefix: 'Hasura'

  # Creat a security group for load balancer and open port 80 in bound from internet
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        !Join [
          '-',
          [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'LoadBalancerSecurityGroup'],
        ]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  # Creat a security group for Containers and open in bound Container port from Load balancer security group to the Container
  TimescaleContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        !Join [
          '-',
          [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'Timescale ContainerSecurityGroup'],
        ]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref TimescaleContainerPort
          ToPort: !Ref TimescaleContainerPort
          CidrIp: 172.10.0.0/16

  # Creat a security group for Containers and open in bound Container port from Load balancer security group to the Container
  HasuraContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        !Join [
          '-',
          [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'Hasura ContainerSecurityGroup'],
        ]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref HasuraContainerPort
          ToPort: !Ref HasuraContainerPort
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup

  # Create a LoadBalancer and attach the Security group and Subnets
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
      Type: application

  # Create a TargetGroup for HTTP port 80
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join ['-', [!Ref ResourcePrefix, 'Hasura']]
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VPC
      HealthCheckEnabled: true

  # Create a LoadBalancerListener and attach the TargetGroup and LoadBalancer
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  # Create a HTTPS LoadBalancerListener and attach the TargetGroup and LoadBalancer
  HttpsLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Certificates:
        - CertificateArn: !Ref HasuraDomainCertificateArn
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08

  # Create a DNS record for the specified Hosted Zone and subdomain
  Route53DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        EvaluateTargetHealth: true
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref HasuraDomainName
      Type: A

  # Create a ECS Service for the Timescale DB task
  TimescaleECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: timescale
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TimescaleTaskDefinition
      DesiredCount: 1
      LaunchType: EC2
      EnableExecuteCommand: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
          SecurityGroups:
            - !Ref TimescaleContainerSecurityGroup
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn
          Port: !Ref TimescaleContainerPort

  # Create an ECS Service and add created Cluster, TaskDefintion, Subnets, TargetGroup and SecurityGroup
  HasuraECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - LoadBalancerListener
      - HttpsLoadBalancerListener
      - TimescaleECSService
    Properties:
      ServiceName: hasura
      Cluster: !Ref Cluster
      TaskDefinition: !Ref HasuraTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      EnableExecuteCommand: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref HasuraContainerSecurityGroup
      LoadBalancers:
        - ContainerName:
            !Join ['-', [!Ref ResourcePrefix, !Ref 'AWS::AccountId', 'Hasura']]
          ContainerPort: !Ref HasuraContainerPort
          TargetGroupArn: !Ref TargetGroup
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn
          Port: !Ref HasuraContainerPort
