CREATE TABLE "public"."serum_events" (
  "serum_market_address" Text,
  "type" Text,
  "timestamp" timestamp NOT NULL,
  "slot" bigint,
  "version" integer,
  "id" text,
  "side" side,
  "price" numeric,
  "size" numeric,
  "order_id" text,
  "client_id" text,
  "account" text,
  "account_slot" integer,
  "fee_tier" integer,
  "fee_cost" numeric,
  "maker" boolean,
  "pk_to_drop" serial NOT NULL,
  PRIMARY KEY ("pk_to_drop"),
  FOREIGN KEY ("serum_market_address") REFERENCES "public"."serum_markets"("address") ON UPDATE restrict ON DELETE restrict,
  FOREIGN KEY ("type") REFERENCES "public"."serum_vial_event_types"("value") ON UPDATE restrict ON DELETE restrict
);
